services:
  nextunnel-server:
    build: .
    container_name: nextunnel-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/config:/usr/local/nextunnel/config
      - ./volumes/certs:/usr/local/nextunnel/certs
      - ./volumes/logs:/usr/local/nextunnel/logs
