[server]
host = "127.0.0.1"
port = 25930

[logs]
file = "logs/nextunnel-server.log"
level = "info"
maxSize = "100MB"
maxBackups = 30
maxAge = 7

[tls]
dir = "certs"

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "nextunnel"
db = "nextunnel"

[geoip]
db_path = "geoip/GeoLite2-City.mmdb"
locales = ["en"]
