[server]
host = "127.0.0.1"
port = 25930

[client]
id = ""

[cert]
ca_file = "certs/ca.crt" # If using Docker to start, this parameter must be in /etc/nextunnel/certs/ca.crt
cert_file = "certs/client.crt" # If using Docker to start, this parameter must be in /etc/nextunnel/certs/client.crt
key_file = "certs/client.key" # If using Docker to start, this parameter must be in /etc/nextunnel/certs/client.key

[logs]
file = "logs/nextunnel-client.log" # If using Docker to start, this parameter must be in /var/log/nextunnel/nextunnel-client.log
level = "info" # allowed: info, warn, error
maxSize = "100MB"
maxBackups = 30
maxAge = 7

[[proxies]]
name = "ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 2222
