[server]
addr = "127.0.0.1"
port = 30985
ip_blacklist = []

[logs]
file = "logs/nextunnel-server.log"
level = "info"

[tls]
ca_file = "certs/ca.crt"
cert_file = "certs/server.crt"
key_file = "certs/server.key"
