[server]
addr = "127.0.0.1"
port = 25930
ip_blacklist = []

[logs]
file = "logs/nextunnel-server.log"
level = "info"

[tls]
dir = "certs"

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "nextunnel"
db = "nextunnel"
