services:
  nextunnel-client:
    build: ../..
    container_name: nextunnel-client
    restart: unless-stopped
    network_mode: host
    environment:
      - NEXTUNNEL_TYPE=client
    volumes:
      - ./volumes/nextunnel/conf/nextunnel-client.toml:/app/conf/nextunnel-client.toml
      - ./volumes/nextunnel/logs:/app/logs
      - ./volumes/nextunnel/certs:/app/certs
